-- 创建 PromptStore 的全文索引
create table
  prompts (
    id bigint generated by default as identity not null,
    prompt text null,
    type bigint null,
    fts tsvector generated always as (to_tsvector('english'::regconfig, prompt)) stored
) tablespace pg_default;
create index fts_idx on prompts using gin(fts);
